### ISSUE TITLE
Mssing documentation - Websocket

### ISSUE THREAD

**Issue by alf1e** [tweechat/doc#1]
Any documentation of a web socket or receive messages is undocumented

**Comment by alf1e** [comment]
https://github.com/tweechat/Trunk/issues/1

**Comment by randomairborne** [comment]
I'm actually not sure how the websocket is going to work yet, i would value feedback on how to set it up

**Comment by alf1e** [comment]
> 

id suggest sort of like your fetch mechanism but when message received it dispatches that on a websocket

**Comment by randomairborne** [comment]
I may implement a map, where events of different types are sent together

**Comment by alf1e** [comment]
ok

**Comment by randomairborne** [comment]
This is now available at https://doc.twee.chat/railway
